describe("Narcissistic function", function()
	it("works for sample cases", function()
		local narcissistic = require("lib.narcissistic")
		assert.are.same(true, narcissistic(7), "7 is narcissistic")
		assert.are.same(true, narcissistic(371), "371 is narcissistic")
		assert.are.same(false, narcissistic(122), "122 is not narcissistic")
		assert.are.same(false, narcissistic(4887), "4887 is not narcissistic")
	end)
end)
